# Generated by Django 5.0.4 on 2024-05-19 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0004_concepto_alter_publicacion_precio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concepto',
            options={'verbose_name': 'Concepto', 'verbose_name_plural': 'Conceptos'},
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudades', to='publicacion.pais'),
        ),
    ]
